[workspace]
release_commits = "^(feat|fix)[(:!]"
publish = false
git_release_enable = false

[[package]]
name = "ironlark-macros"
version_group = "sdk"
changelog_update = false
git_tag_enable = false

[[package]]
name = "ironlark"
version_group = "sdk"
changelog_path = "./CHANGELOG.md"
git_tag_name = "v{{ version }}"
