//! The items a mod's schema reaches Rust as.
//!
//! One type per message, generated by prost, and the declaration written onto
//! that type: the verbs take the payload itself, so what a payload declares has
//! to be readable from the payload and nowhere else. A message declaring twice
//! is then a second impl of one trait for one type, which is a coherence error
//! the compiler words before this macro has to.
//!
//! Beside the types stands a module per kind, re-exporting the ones that
//! declare. It is the index of what a mod declares, not a second set of items:
//! `signal::Latch` and `Latch` are one type.
//!
//! A name this mod borrows is re-exported one module deeper, under the owner it
//! belongs to, and its declaration carries the qualified name the host resolves
//! it by. That keeps a borrowed `pressed` and an own `pressed` apart without
//! either renaming the other.

use super::declaration::{Origin, PayloadType, Realm, Request, Signal};
use super::generate::Generated;
use super::read::Declarations;
use proc_macro2::{Ident, Span, TokenStream};
use quote::quote;
use syn::LitStr;

/// The generated types and the declarations, as one expansion.
pub(crate) fn expand(
    schema: &LitStr,
    declarations: &Declarations,
    payloads: Vec<Generated>,
) -> syn::Result<TokenStream> {
    let Some(own) = payloads.first().map(|generated| generated.module.clone()) else {
        return Err(syn::Error::new(
            schema.span(),
            "the schema generated no types at all",
        ));
    };

    let modules = payloads.iter().map(|generated| {
        let (module, types) = (&generated.module, &generated.types);
        let doc = format!("The types the `{module}` schema describes.");
        quote! {
            #[doc = #doc]
            pub mod #module {
                #types
            }
        }
    });

    let signals = Kind::signal(&declarations.signals);
    let requests = Kind::request(schema, &declarations.requests)?;
    let specs = declarations
        .signals
        .iter()
        .map(signal_spec)
        .chain(declarations.requests.iter().map(request_spec));

    let signal_module = signals.module("signal", "signals");
    let request_module = requests.module("request", "requests");

    Ok(quote! {
        // Re-reads the schema on every build of this crate, so an edit to it
        // generates the types and the declarations again.
        const __IRONLARK_SCHEMA_TRACKED: &str =
            include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/", #schema));

        #(#modules)*

        /// This mod's own payload types, reached without naming its schema.
        pub use #own::*;

        #signal_module

        #request_module

        #(#specs)*
    })
}

/// One kind's index: this mod's own declarations, and each owner's beneath it.
#[derive(Default)]
struct Kind {
    own: Vec<TokenStream>,
    borrowed: Vec<Borrowed>,
}

/// One owner's borrowed declarations, in the module named for its schema.
struct Borrowed {
    module: Ident,
    owner: String,
    listed: Vec<TokenStream>,
}

impl Kind {
    fn signal(signals: &[Signal]) -> Self {
        let mut kind = Self::default();
        for signal in signals {
            let doc = match &signal.origin.owner {
                None => format!(
                    "The declared signal `{}`. The raise verbs take a value of it, and `observe` \
                     hears one.",
                    signal.name
                ),
                Some(owner) => format!(
                    "The signal `{}`, borrowed from `{owner}`. The raise verbs take a value of \
                     it, and `observe` hears one.",
                    signal.name
                ),
            };
            kind.push(&signal.origin, &signal.payload, &doc);
        }
        kind
    }

    /// A request is read from the mod's own schema alone. An imported `service`
    /// lists nothing here: borrowing an answer surface is not ruled, so there
    /// is no name for it to be reached under.
    fn request(schema: &LitStr, requests: &[Request]) -> syn::Result<Self> {
        let mut kind = Self::default();
        for request in requests {
            if request.realm != Realm::Server {
                return Err(syn::Error::new(
                    schema.span(),
                    format!(
                        "`{}` sits in `service {}`, and a request answered by the client half is \
                         not served; move it to `service {}`",
                        request.name,
                        Realm::Client,
                        Realm::Server
                    ),
                ));
            }
            let doc = format!(
                "The declared request `{}`. `request` takes a value of it and answers with its \
                 response type.",
                request.name
            );
            kind.push(&request.origin, &request.payload, &doc);
        }
        Ok(kind)
    }

    /// Lists one declaration in its kind's module, as a re-export of the type
    /// the schema generated rather than an item of its own.
    fn push(&mut self, origin: &Origin, payload: &PayloadType, doc: &str) {
        let module = &origin.module;
        if origin.owner.is_none() {
            self.own.push(quote! {
                #[doc = #doc]
                pub use super::#module::#payload;
            });
            return;
        }
        let listed = quote! {
            #[doc = #doc]
            pub use super::super::#module::#payload;
        };
        match self.borrowed.iter_mut().find(|held| held.module == *module) {
            Some(held) => held.listed.push(listed),
            None => self.borrowed.push(Borrowed {
                module: module.clone(),
                owner: origin.owner.iter().map(ToString::to_string).collect(),
                listed: vec![listed],
            }),
        }
    }

    /// The kind's module, or nothing where the kind declares nothing.
    fn module(&self, name: &str, plural: &str) -> Option<TokenStream> {
        if self.own.is_empty() && self.borrowed.is_empty() {
            return None;
        }
        let held = &self.own;
        let borrowed = self.borrowed.iter().map(|owner| {
            let (module, listed) = (&owner.module, &owner.listed);
            let doc = format!(
                "The {plural} this mod borrows from `{}`, one entry each.",
                owner.owner
            );
            quote! {
                #[doc = #doc]
                pub mod #module {
                    #(#listed)*
                }
            }
        });
        let name = Ident::new(name, Span::call_site());
        let doc = format!(
            "The {plural} this mod's schema declares, one entry each. Each is the payload type \
             itself, re-exported, not a second item standing for it."
        );
        Some(quote! {
            #[doc = #doc]
            pub mod #name {
                #(#held)*
                #(#borrowed)*
            }
        })
    }
}

fn signal_spec(signal: &Signal) -> TokenStream {
    let (module, payload) = (&signal.origin.module, &signal.payload);
    // A bare name is the caller's own declaration; the host reads a name
    // carrying `:` as a declared reference to the mod that owns it.
    let name = match &signal.origin.owner {
        None => signal.name.to_string(),
        Some(owner) => format!("{owner}/signal/{}", signal.name),
    };
    let (audience, transit) = (signal.audience, signal.transit);
    quote! {
        impl ::ironlark::protocol::SignalSpec for #module::#payload {
            type Audience = #audience;
            const NAME: &'static str = #name;
            const TRANSIT: ::ironlark::protocol::Transit = #transit;
        }
    }
}

fn request_spec(request: &Request) -> TokenStream {
    let (module, payload) = (&request.origin.module, &request.payload);
    let (name, response) = (request.name.as_str(), &request.response);
    quote! {
        impl ::ironlark::protocol::RequestSpec for #module::#payload {
            type Response = #module::#response;
            const NAME: &'static str = #name;
        }
    }
}
